# Generated by Django 5.2.8 on 2025-12-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="max_strength",
            field=models.IntegerField(),
        ),
    ]
