# Generated by Django 5.2.8 on 2025-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_user_delete_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
