# Generated by Django 5.2.8 on 2025-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_classroom_max_strength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="max_strength",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="section",
            field=models.CharField(max_length=10),
        ),
    ]
