# Generated by Django 5.2.9 on 2025-12-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_syllabus_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignsubject",
            name="subject_name",
        ),
        migrations.AddField(
            model_name="assignsubject",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.subject",
            ),
        ),
    ]
