# Generated by Django 5.2.8 on 2025-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_alter_classroom_max_strength_alter_classroom_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="max_strength",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="syllabus_file",
            field=models.FileField(upload_to="syllabus/"),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="timetable_file",
            field=models.FileField(upload_to="timetable/"),
        ),
    ]
