# Generated by Django 5.2.8 on 2025-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_alter_classroom_max_strength_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
