# Generated by Django 5.2.8 on 2025-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_user_admission_no_user_dob_user_mobile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
