# Generated by Django 5.2.8 on 2025-11-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_adminuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUser",
        ),
    ]
