# Generated by Django 5.2.8 on 2025-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_delete_adminuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admission_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mobile",
        ),
        migrations.AddField(
            model_name="user",
            name="class_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
