# Generated by Django 5.2.8 on 2025-12-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_user_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="class_name",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="login.classroom",
            ),
        ),
    ]
