# Generated by Django 5.2.8 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_remove_user_admission_no_remove_user_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admission_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("teacher", "Teacher"),
                    ("principal", "Principal"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
